
import { BarcodePrintButton } from "@/components/printing/barcode-labels"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { SkuAPI } from "@/services/api"
import { Product, SKU } from "@/types/schema"
import { Edit, ScanLine, Trash2 } from "lucide-react"
import { useEffect, useState } from "react"
import { toast } from "sonner"

interface SkuManagerProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    product: Product
    onUpdate: () => void 
}

function SkuForm({ 
    product, skus, setSkus, editingSkuId, setEditingSkuId, handleCancelEdit, onUpdate 
}: { 
    product: Product, skus: SKU[], setSkus: any, editingSkuId: number | null, setEditingSkuId: any, handleCancelEdit: () => void, onUpdate: () => void 
}) {
    const [attributes, setAttributes] = useState("")
    const [price, setPrice] = useState("")
    const [costPrice, setCostPrice] = useState("")
    const [stock, setStock] = useState("")
    const [skuCode, setSkuCode] = useState("")
    const [barcode, setBarcode] = useState("")
    const [barcodeType, setBarcodeType] = useState<"EAN13" | "INTERNO">("INTERNO")
    const [isAutoGenerated, setIsAutoGenerated] = useState(false)
    const [loading, setLoading] = useState(false)

    // Sincronizar estado cuando se edita un SKU diferente
    useEffect(() => {
        if (editingSkuId) {
            const sku = skus.find(s => s.id === editingSkuId)
            if (sku) {
                setSkuCode(sku.code)
                const attrString = sku.variantOptions?.map(v => `${v.name}: ${v.value}`).join(', ') || ""
                setAttributes(attrString)
                setPrice(String(sku.price))
                setCostPrice(sku.costPrice ? String(sku.costPrice) : "")
                setStock(String(sku.stock))
                setBarcode(sku.barcode || "")
                setBarcodeType(sku.barcodeType || "INTERNO")
                setIsAutoGenerated(sku.isAutoGenerated || false)
            }
        } else {
            setSkuCode("")
            setAttributes("")
            setPrice("")
            setCostPrice("")
            setStock("")
            setBarcode("")
            setBarcodeType("INTERNO")
            setIsAutoGenerated(false)
        }
    }, [editingSkuId, skus])

    const handleSubmit = async () => {
        if (!attributes && !editingSkuId) return alert("Ingrese atributos")
        
        setLoading(true)
        try {
            const validAttributes = attributes.split(',').map(part => {
                const parts = part.split(':').map(s => s.trim())
                if (parts.length < 2) return { name: 'Variante', value: parts[0] || 'Unico' }
                return { name: parts[0], value: parts[1] }
            })

            const payload = {
                price: parseFloat(price) || product.basePrice,
                costPrice: parseFloat(costPrice) || 0,
                ...(editingSkuId ? {} : { stock: parseInt(stock) || 0 }),
                attributes: validAttributes,
                ...(editingSkuId && skuCode ? { code: skuCode } : {}),
                barcode: isAutoGenerated ? undefined : barcode,
                barcodeType,
                isAutoGenerated
            }

            if (editingSkuId) {
                const updated = await SkuAPI.update(editingSkuId, payload)
                setSkus(skus.map(s => s.id === editingSkuId ? updated : s))
            } else {
                const newSkuData = {
                   ...payload,
                   productId: product.id,
                   code: skuCode || `${product.model || 'PROD'}-${Math.random().toString(36).substr(2, 5).toUpperCase()}`,
                }
                const created = await SkuAPI.create(newSkuData)
                setSkus([...skus, created])
            }
            
            handleCancelEdit()
            onUpdate()
        } catch (error) {
            alert("Error al guardar variante")
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className={`sm:p-4 sm:w-full w-[80%] p-1 rounded-lg border transition-colors max-h-[60vh] overflow-y-auto ${editingSkuId ? 'bg-secondary/5 border-secondary/20' : 'bg-muted/30 border-border'}`}>
            <div className="flex items-center justify-between mb-4">
                <h4 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">
                    {editingSkuId ? 'Editar Variante' : 'Nueva Variante'}
                </h4>
                {editingSkuId && (
                    <Button variant="ghost" size="sm" onClick={handleCancelEdit} className="h-6 text-xs text-muted-foreground hover:text-foreground hover:cursor-pointer">
                        Cancelar Edición
                    </Button>
                )}
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                <div className="md:col-span-4 space-y-2">
                    <Label className="text-foreground">Atributos (Ej: Color: Rojo, Talle: L)</Label>
                    <Input 
                        value={attributes} 
                        onChange={(e) => setAttributes(e.target.value)} 
                        placeholder="Color: Rojo, Talle: L" 
                        className="bg-background border-input placeholder:text-muted-foreground text-foreground font-medium" 
                    />
                </div>
               
                <div className="md:col-span-2 space-y-2">
                    <Label className="text-foreground">Precio</Label>
                    <Input 
                        type="number" 
                        inputMode="decimal"
                        value={price} 
                        onChange={(e) => setPrice(e.target.value)} 
                        placeholder={String(product.basePrice)} 
                        className="bg-background border-input placeholder:text-muted-foreground text-foreground font-medium" 
                    />
                </div>
                <div className="md:col-span-2 space-y-2">
                    <Label className="text-foreground">Costo Compra</Label>
                    <Input 
                        type="number" 
                        inputMode="decimal"
                        value={costPrice} 
                        onChange={(e) => setCostPrice(e.target.value)} 
                        placeholder="Costo" 
                        className="bg-background border-input placeholder:text-muted-foreground text-foreground font-medium" 
                    />
                </div>
                <div className="md:col-span-2 space-y-2">
                    <Label className="text-foreground">Stock</Label>
                    <Input 
                        type="number" 
                        inputMode="decimal"
                        value={stock} 
                        onChange={(e) => setStock(e.target.value)} 
                        placeholder="0" 
                        disabled={true}
                        title="El stock solo se modifica mediante Compras o Ventas"
                        className="bg-muted border-input placeholder:text-muted-foreground text-muted-foreground font-medium cursor-not-allowed" 
                    />
                    <p className="text-[10px] text-muted-foreground leading-tight">
                        Gestionado por Compras/Ventas
                    </p>
                </div>
                <div className="md:col-span-4 space-y-2">
                    <Label className="text-foreground">Código SKU (Opcional)</Label>
                    <Input 
                        value={skuCode} 
                        onChange={(e) => setSkuCode(e.target.value)} 
                        placeholder="Auto-generado si se deja vacio" 
                        className="bg-background border-input placeholder:text-muted-foreground text-foreground font-medium" 
                    />
                </div>

                <div className="md:col-span-4 p-4 border rounded-lg bg-muted/20 space-y-4">
                    <h4 className="font-semibold text-sm flex items-center gap-2 text-foreground">
                        <ScanLine className="w-4 h-4" /> Configuración de Código de Barras
                    </h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label>Tipo de Código</Label>
                            <Select 
                                value={barcodeType} 
                                onValueChange={(val: "EAN13" | "INTERNO") => setBarcodeType(val)}
                            >
                                <SelectTrigger className="bg-background">
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="INTERNO">Interno / Alfanumérico</SelectItem>
                                    <SelectItem value="EAN13">EAN-13 (Estándar)</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        {barcodeType === 'EAN13' && (
                            <div className="flex items-center space-x-2 pt-8">
                                <Switch 
                                    id="auto-gen" 
                                    checked={isAutoGenerated}
                                    onCheckedChange={setIsAutoGenerated}
                                />
                                <Label htmlFor="auto-gen">Generar Automáticamente</Label>
                            </div>
                        )}

                        {!isAutoGenerated && (
                            <div className="col-span-2 md:col-span-1 space-y-2 ">
                                <Label>Código {barcodeType}</Label>
                                <Input 
                                    value={barcode} 
                                    inputMode={barcodeType === 'EAN13' ? 'numeric' : 'text'}
                                    onChange={(e) => setBarcode(e.target.value)}
                                    placeholder={barcodeType === 'EAN13' ? "779..." : "ABC-123..."} 
                                    className="bg-background"
                                />
                                {barcodeType === 'EAN13' && barcode.length > 0 && barcode.length !== 13 && (
                                    <p className="text-xs text-red-500 font-bold">Debe tener 13 dígitos</p>
                                )}
                            </div>
                        )}
                    </div>
                </div>

                <Button onClick={handleSubmit} disabled={loading} className={`text-secondary-foreground md:col-span-4 ${editingSkuId ? 'bg-emerald-600 hover:bg-emerald-700' : 'bg-secondary hover:bg-secondary/90'} shadow-sm hover:cursor-pointer`}>
                    {editingSkuId ? 'Actualizar Variante' : 'Agregar Variante'}
                </Button>
            </div>
        </div>
    )
}

export function SkuManager({ open, onOpenChange, product, onUpdate }: SkuManagerProps) {
    const [skus, setSkus] = useState<SKU[]>(product.skus || [])
    const [editingSkuId, setEditingSkuId] = useState<number | null>(null)
    const [skuToDelete, setSkuToDelete] = useState<number | null>(null)

    useEffect(() => {
        setSkus(product.skus || [])
        setEditingSkuId(null)
    }, [product.id, product.skus])

    const handleEditClick = (sku: SKU) => {
        setEditingSkuId(sku.id)
    }

    const handleCancelEdit = () => {
        setEditingSkuId(null)
    }

  
    useEffect(() => {
        if (!open) {
            handleCancelEdit()
        }
    }, [open])

    const handleDeleteSku = async () => {
        if (!skuToDelete) return;
        const id = skuToDelete;
       
        const toastId = toast.loading("Eliminando variante...");
        try {
            await SkuAPI.delete(id)
         
            setSkus(skus.filter(s => s.id !== id))
            onUpdate()
          
        } catch (error: any) {
            
            const message = error.response?.data?.message || "No se pudo eliminar la variante. Intente nuevamente.";
            toast.error(message, { id: toastId });
        } finally {
            setSkuToDelete(null);
        }
    }

    return (
        <>
        <Dialog open={open} onOpenChange={(val) => {
            if (!val) handleCancelEdit()
            onOpenChange(val)
        }}>
            <DialogContent className="sm:w-auto w-[95%] max-h-[90vh] overflow-y-auto overflow-x-auto text-foreground border-4 border-secondary/60 shadow-2xl ">
                <DialogHeader className="sm:w-full w-[100%]">
                    <DialogTitle className="text-xl font-bold text-foreground">Gestión de Variantes</DialogTitle>
                    <DialogDescription className="text-muted-foreground">
                        Administre las variantes (SKUs) para: <span className="font-semibold text-secondary">{product.name}</span>
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-6 py-4">
                    <SkuForm 
                        product={product} 
                        skus={skus} 
                        setSkus={setSkus} 
                        editingSkuId={editingSkuId} 
                        setEditingSkuId={setEditingSkuId} 
                        handleCancelEdit={handleCancelEdit} 
                        onUpdate={onUpdate} 
                    />

                    {/* Lista */}
                    <div className="border border-border rounded-lg sm:overflow-hidden overflow-x-auto shadow-sm sm:w-full w-[80%] ">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-muted/50 text-muted-foreground font-semibold border-b border-border">
                                <tr>
                                    <th className="px-4 py-3">Código</th>
                                    <th className="px-4 py-3">Atributos</th>
                                    <th className="px-4 py-3">Precio</th>
                                    <th className="px-4 py-3">Costo</th>
                                    <th className="px-4 py-3">Stock</th>
                                    <th className="px-4 py-3 text-right"></th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-border bg-background">
                                {skus.map((sku) => (
                                    <tr key={sku.id} className={`hover:bg-muted/50 transition-colors ${editingSkuId === sku.id ? 'bg-secondary/10' : ''}`}>
                                        <td className="px-4 py-3 font-mono text-foreground">{sku.code}</td>
                                        <td className="px-4 py-3 font-medium text-foreground">
                                            {sku.variantOptions?.map(v => `${v.name}: ${v.value}`).join(', ') || 'Default'}
                                        </td>
                                        <td className="px-4 py-3 text-foreground">${sku.price}</td>
                                        <td className="px-4 py-3 text-foreground">${sku.costPrice || 0}</td>
                                        <td className="px-4 py-3 text-foreground">{Number(sku.stock).toFixed(3).replace(/\.?0+$/, '')}</td>
                                        <td className="px-4 py-3 text-right space-x-2">
                                            <Button 
                                                variant="ghost" 
                                                size="sm" 
                                                onClick={() => handleEditClick(sku)}
                                                className="text-secondary hover:cursor-pointer hover:text-secondary hover:bg-secondary/10"
                                            >
                                                <Edit className="h-4 w-4" />
                                            </Button>
                                            <BarcodePrintButton skus={[{ ...sku, product }]} />
                                            <Button 
                                                variant="ghost" 
                                                size="sm" 
                                                onClick={() => setSkuToDelete(sku.id)}
                                                className="text-destructive hover:cursor-pointer hover:text-destructive hover:bg-destructive/10"
                                            >
                                                <Trash2 className="h-4 w-4" />
                                            </Button>
                                        </td>
                                    </tr>
                                ))}
                                {skus.length === 0 && (
                                    <tr>
                                        <td colSpan={5} className="px-4 py-12 text-center text-muted-foreground border-dashed">
                                            <div className="flex flex-col items-center justify-center gap-2">
                                                <div className="p-3 rounded-full bg-muted">
                                                    <Edit className="h-6 w-6 text-muted-foreground" />
                                                </div>
                                                <p>No hay variantes registradas</p>
                                            </div>
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>

                <DialogFooter className="border-t border-border px-6 py-4 sm:w-full w-[80%] ">
                    <Button variant="outline" onClick={() => onOpenChange(false)} className="border-gray-300 text-foreground hover:bg-muted hover:cursor-pointer">
                        Cerrar
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>

        <Dialog open={!!skuToDelete} onOpenChange={(val) => !val && setSkuToDelete(null)}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Confirmar Eliminación</DialogTitle>
                    <DialogDescription>
                        ¿Está seguro de que desea eliminar esta variante? Esta acción no se puede deshacer, pero conservaremos el historial de ventas si lo tiene.
                    </DialogDescription>
                </DialogHeader>
                <DialogFooter className="gap-2 sm:gap-0">
                    <Button variant="outline" onClick={() => setSkuToDelete(null)} className="hover:cursor-pointer">
                        Cancelar
                    </Button>
                    <Button variant="destructive" onClick={handleDeleteSku} className="hover:cursor-pointer">
                        Eliminar Variante
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
        </>
    )
}
