export type PaymentStatus = 'PENDING' | 'PAID' | 'CANCELLED' | 'REJECTED' |'SHIPPED';
export type PaymentType = 'CASH' | 'DEBIT' | 'CARD' | 'TRANSFER' | 'MERCADO_PAGO' | 'POINTS';
export type DeliveryType = 'PICKUP' | 'DELIVERY';
export type DeliveryStatus = 'PENDING_DELIVERY' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
export type UserRole = 'SUPER_ADMIN' | 'ADMIN' | 'EMPLOYEE' | 'CUSTOMER';
export type UserStatus = 'ACTIVE' | 'SUSPENDED' | 'DELETED';
export type Condition = 'NEW' | 'USED' | 'REFURBISHED' | 'EXHIBITION';
export type DiscountType = 'PERCENTAGE' | 'FIXED_AMOUNT' | 'FIXED_PRICE';

export interface Category {
  id: number;
  name: string;
  slug: string;
  parentId?: number | null;
  children?: Category[];
}

export interface Currency {
  id: number;
  code: string;
  symbol: string;
  exchangeRateToBase: number;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ProductPrice {
  id: number;
  productId: number;
  currencyCode: string;
  price: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface Product {
  id: number;
  name: string;
  type: string;
  brand: string;
  model?: string | null;
  description: string;
  basePrice: number; 

  pointsReward: number;
  images: string[];
  condition: Condition;
  qr?: string | null;
  isTrending: boolean;
  isRecommended: boolean;
  isNew: boolean;
  isActive: boolean;
  measurementUnit?: string;
  allowFractional?: boolean;
  categoryId: number;
  category?: Category;
  skus?: SKU[];
  createdAt: string;
  updatedAt: string;
  characteristics?: { key: string; value: string }[];
  specifications?: { key: string; value: string }[];
}

export interface SKU {
  id: number;
  code: string;
  price: number; 
  stock: number;
  soldQuantity: number;
  active: boolean;
  productId: number;
  product?: Product;
  variantOptions?: VariantOption[];
  
  // Sistema de Código de Barras
  barcode?: string;
  barcodeType?: "EAN13" | "INTERNO";
  isAutoGenerated?: boolean;
}

export interface VariantOption {
  id: number;
  name: string;
  value: string;
  skuId: number;
}

export interface Role {
  id: number;
  name: string; 
  permissions?: any[];
}

export interface User {
  id: number;
  name: string;
  email: string;
  roleId: number; 
  role?: Role; 
  status: UserStatus;
  dni?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  state?: string | null;
  zipCode?: string | null;
  points: number;
  branchId?: number | null;
  branch?: Branch;
  adminBranches?: UserBranch[];
  sales?: { branchId: number }[];
  isGuest?: boolean;
  createdAt?: string; 
  updatedAt?: string;
}

export interface UserBranch {
  userId: number;
  branchId: number;
  branch?: Branch;
}

export interface SaleItem {
  id?: number;
  productName: string;
  skuCode: string;
  unitPrice: number;
  quantity: number;
  subtotal: number;
  skuId?: number | null;
  sku?: SKU; 
  brand?: string;
  pointsReward?: number;
  measurementUnit?: string;
  allowFractional?: boolean;
}

export interface Coupon {
  id: number;
  code: string;
  type: string;
  value: number;
}

export interface Sale {
  id?: number; 
  uuid?: string;
  userId: number;
  user?: User;
  employeeId?: number | null;
  employee?: User;
  total: number;
  subtotal: number;
  discount: number;
  observations?:string;
  coupon?: Coupon | null;
  shippingCost: number;
  currencyCode: string;
  paymentStatus: PaymentStatus;
  paymentType: PaymentType;
  mpPaymentId?: string | null;
  deliveryType: DeliveryType;
  deliveryStatus: DeliveryStatus;
  deliveryAddress?: string | null;
  items: SaleItem[];
  paymentProofUrl?: string | null;
  paymentProofUploadedAt?: string | null;
  branch?: Branch;
  receipt?: any; 
  createdAt?: string;
  updatedAt?: string;
}

export interface CartItem extends SaleItem {
  tempId: string;
  maxStock: number;
  categoryId?: number;
  productId?: number;
}

export type TransferStatus = 'PENDING' | 'APPROVED' | 'REJECTED';

export interface Transfer {
  id: number;
  userId: number;
  user?: {
    id: number;
    name: string;
    email: string;
    dni?: string;
    phone?: string;
  };
  amount: number;
  imageUrl: string;
  status: TransferStatus;
  createdAt: string;
  updatedAt?: string;
  branchId?: number; 
}

export interface Branch {
  id: number;
  name: string;
  code: string;
  address: string;
  city?: string | null;
  state?: string | null;
  phone?: string | null;
  email?: string | null;
  isActive: boolean;
  isHeadquarters: boolean;
  operatingHours?: any;
  latitude?: number | string | null;
  longitude?: number | string | null;
}

export type StockTransferStatus = 'PENDING' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';

export interface StockTransferItem {
  id: number;
  transferId: number;
  skuId: number;
  quantity: number;
  sku?: SKU;
}

export interface StockTransfer {
  id: number;
  originBranchId: number;
  destinationBranchId: number;
  userId: number;
  status: StockTransferStatus;
  notes?: string;
  createdAt: string;
  updatedAt?: string;
  items: StockTransferItem[];
  originBranch?: Branch;
  destinationBranch?: Branch;
  user?: User;
}

export type SupplierPaymentMethod = 'CASH' | 'TRANSFER' | 'CHECK' | 'DEBIT' | 'CARD' | 'MERCADO_PAGO' | 'OTRO';

export interface SupplierPayment {
  id: number;
  supplierId: number;
  supplier?: {
    id: number;
    tradeName: string;
  }; 
  purchaseId?: number | null;
  amount: number;
  method: SupplierPaymentMethod;
  paymentDate: string;
  reference?: string | null;
  description?: string | null;
  createdBy: number;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseItem {
    id: number;
    skuId: number;
    quantity: number;
    unitPrice: number;
    subtotal: number;
    sku: {
        code: string;
        product: {
            name: string;
            images: string[];
        };
        variantOptions?: VariantOption[];
    };
}

export interface Purchase {
    id: number;
    branchId: number;
    supplierId: number;
    userId: number;
    status: string;
    estimatedTotal: number; 
    deliveryDate?: string;
    notes?: string;
    createdAt: string;
    updatedAt: string;
    items?: PurchaseItem[];
    branch?: Branch;
    supplier?: any;
    user?: User;
    payment?: SupplierPayment | null;
}

export interface ShippingZone {
    id: number;
    country?: string | null;
    province?: string | null;
    city?: string | null;
    cost: number;
    active: boolean;
}
